### ISSUE TITLE
ctrl+o is doesn't work in she latest editor

### ISSUE THREAD

**Issue by alyadan** [XVimProject/XVim#774]
Now it can not back to the previous tag, but it can work in the before.

**Comment by obryanlouis** [comment]
+1. In XCode7, ctrl+o crashes the editor too.

**Comment by pebble8888** [comment]
Now C-o and C-i use XVim jump list.
If you use Xcode jump history by C-o and C-i, set your .xvimrc file this.
```
"Go Back
map <C-o> :pjump<CR>
"Go Forward
map <C-i> :njump<CR>
```

**Comment by neybis** [comment]
C-i is the default binding in Xcode for "Editor->Structure->Re-Indent" so that's potentially part of the problem. It seems as though C-o isn't working either though.

Should we just re-work C-i/C-o to use "Go Forward" and "Go Back" respectively?? I think I'll have a pull request here pretty soon with a lot of missing keybindings related to folding and navigation. Perhaps I could include this as a part of the request.

**Comment by pebble8888** [comment]
I prefer to use Xcode jump history by C-o and C-i personally.
But Some people prefer vim jump history that is bounty source functionality #626.
If you will PR, please enable anyone easily to toggle two modes without build XVim.

**Comment by alyadan** [comment]
thanks for you help

**Comment by neybis** [comment]
Is the behavior of C-o and C-i currently working? When I tested develop branch it seemed to be broken (even after removing the default Xcode keybinding for "Re-Indent").

If it's just me seeing this issue, we should obviously close this out as having the jump list functionality as referenced in #626 is ideal for most users. However, if the issue is present for everyone, we should re-open this or open a new issue for fixing the problem at hand.

**Comment by grantjk** [comment]
Ctrl o and i stopped working for me entirely. They don't do anything anymore. They used to go back and forth between files, but they just don't do anything at all anymore.

**Comment by pebble8888** [comment]
@neybis
I think C-o and C-i is working.
If you think something broken, please write sample text, your typed command, desired result, actual result and Xvim branch name you use.

By the way, `gd`(jump to definition) motion is NOT inserted jumplist.
At this point, I think there is room for improvement.

**Comment by neybis** [comment]
My apologies @pebble8888, after investigating vim's jumplist functionality and retesting you are correct. Jump lists are working as intended.

@grantjk You probably had the same misunderstanding I did. It is important that only certain motions are inserted into the jumplist; namely searching, substitute and marks (in vim at least). I tested with searches and C-o and C-i do indeed jump through the jumplist as expected.
