### ISSUE TITLE
Some key mapping is also not working in .xvimrc

### ISSUE THREAD

**Issue by carrigmore** [XVimProject/XVim#844]
Some key mapping is also not working in .xvimrc, Ctrl-b works correct in XVim for scrolling page up, but if you try mapping backspace to Ctrl-b, it doesn't work. This works in Vim but not XVim, don't know why.

nmap < space > < c-f > "map space key to scroll down page, works
nmap < backspace > < c-b > "map backspace key to scroll up page, doesn't work, sometimes cursor become double width in app when you press backspace.

![screen shot 2015-10-19 at 17 23 10](https://cloud.githubusercontent.com/assets/8460701/10586077/62f88ffc-7692-11e5-8222-76067006c811.png)

**Comment by neybis** [comment]
At first, I thought that based off of the way the plug-in was written (or designed, rather, for lack of a better term) that this would simply not be possible.

After looking at the behavior a little, 'space' and 'backspace' move the cursor in normal mode by default. Xcode would obviously insert spaces or backspace to remove characters by default. So it is obvious that it should be possible for us to modify Xcode's space and backspace functionality. Following that logic, we should be able to remap it as well.

I think we need to figure out what is broken and what is not. If I had to guess, I would say that not all of the mapping functionality is broken. It is listed as supported in the FeatureList.md and although I’m new to the project, I’d guess it was working at some point. I would rather believe that certain keys are having issues with being bound. Here’s to hoping I’m wrong :P ...or maybe I should be hoping I'm right?? D:

Maybe we can try to test various key-mapping combinations to see what works and what doesn’t?? For example, what if we were to try to map a Ctrl-{some character here} sequence to scroll down page; for example, ‘C-h’ or ‘C-i’?? What about single character mappings that aren’t special characters; for example, ‘h’ all on its own? What about mapping to things that aren't "scroll page down". What about mapping something to, say, "5w" so that it will walk forward 5 words.

I think the more answers we have to these questions, the easier it will be for all of us to figure this out.

**Comment by neybis** [comment]
Can you elaborate on your setup?? ```nmap <space> <c-f>``` and ```nmap <bs> <c-b>``` seem to be working fine on my end.

**Comment by carrigmore** [comment]
@neybis, I tired nmap <bs> <c-b> is working for me. I am using Xcode 7.0. I will test other mapping when I have time, maybe at weekend. Thanks a lot

**Comment by neybis** [comment]
@carrigmore, not a problem :) I just realized the person who opens an issue is also capable of closing it. Just to keep our paperwork up-to-date, if you can close this out once you verified mappings are working as you expect that'd be awesome!

**Comment by JugglerShu** [comment]
Please check if your problem is fixed in develop branch. I make <backspace> to be mapped as well as <bs>. If you have other problems in mapping, let me know.
