### ISSUE TITLE
Cursor not in correct block when using tab as tab in Xcode

### ISSUE THREAD

**Issue by carrigmore** [XVimProject/XVim#847]
The width of block cursor is not single width, (in the same width as a tab, 4 times space) when it is points to a tab in Xcode.

In Xcode set prefer using tab as indention. 
![screen shot 2015-10-21 at 14 25 47](https://cloud.githubusercontent.com/assets/8460701/10637858/ce0473a6-77ff-11e5-95ff-2cca39fab10c.png)
![screen shot 2015-10-21 at 13 55 46](https://cloud.githubusercontent.com/assets/8460701/10637857/cde99108-77ff-11e5-9817-f1549941fbf6.png)
![cursor](https://cloud.githubusercontent.com/assets/8460701/10639247/21657bb0-7807-11e5-801e-21ef01c7e353.gif)

**Comment by neybis** [comment]
I actually like the fact that this highlights the whole tab personally. Perhaps we could make this a configurable option (if it is even possible), but I definitely consider this more of a feature than a bug. Not trying to be rude, but I think there are higher priority things we could focus our efforts on.

That being said, if this is possible I'd recommend making it configurable via xvimrc. We'd probably need _yet another_ proprietary cursor setting (already have blinkcursor and soon blockcursor). The more of these cursor options we get the harder it becomes to understand and use. If we decide to implement this, we probably would want to start investigating alternative ways of configuring cursor settings too.

**Comment by carrigmore** [comment]
@neybis thanks for your reply. Personally I don't think that is a feature if we compare that behavior with vim. Also if you try insert at that point, the width of the cursor is changing from 4 to 3 then to 2 ... the width of cursor should be same and moving while user editing. That is my understanding anyway. Cheers

**Comment by carrigmore** [comment]
@neybis , sorry please don't get me wrong, this can be a feature in normal mode, but in insert mode, it is a bug, as the width of the cursor is reducing as user is input letters, and the cursor is not moving until it's width is reduced to 1. I hope I made myself clear :)

**Comment by neybis** [comment]
Again, not trying to be rude and others can weigh in on this, but this is the correct behavior. Almost all text editors, regardless of whether or not a block cursor is being used, place the cursor where the next character insertion would be. If you are using a block cursor, there are typically two ways to "highlight" the block. The first method uses a predefined block "size" (usually the size of a non-tab character; this is vim's default). The second method uses a block "size" that matches the size of the next character (again, where the next insertion would happen). We currently only support the later.

So in XVim block cursor mode, the next character is enclosed in a rectangle (or block). If that character is a tab, the entire tab will be "highlighted". Tabs change their viewable "size" based off of how many characters prepend it. Normally, you can't really see this directly as tabs are whitespace and the human eye often misses what's not there. But this is why `[self removeObjectFor...` doesn't move as you type characters; because the "size" of the tab character can shrink all the way down to a single character. If you ever try to shrink it more than that, it jumps back to a "normal" tab size and shifts over a tab "column". This is why `[self removeObjectFor...` shifts when you type the 4th character; because your tab settings set a tab width of 4. (Note: If you change your tab width, tabs won't start at 4 characters and shrink down from there, but rather will start at the new value and shrink from that. Try messing around with tab widths of 2 and 8 to see what I mean.)

So wrapping this conversation around full circle, it would actually be a bug if the tab character _didn't_ reduce as you typed. Because that would mean that `[self removeObjectFor...` shifted as you typed. And that's not how tabs work :P

Random tidbit, but this is also why I prefer highlighting the entire tab. If you were to make the block when hovering over a tab smaller, say the size of one space character, it is easy to get confused when text _doesn't_ shift (i.e. you think there are spaces there but there are really tabs). Being able to differentiate space indentation from tab indentation just from looking at the cursor is _extremely_ helpful to me and I cannot imagine doing it any other way.

**Comment by carrigmore** [comment]
@neybis I really appreciate your very detailed explanation. Now I understand this is the correctly behavior. Really appreciate the time you spend on explain this for me. I don't even image that you would explain that in such detail. Thanks again :) I am happy to close this now

**Comment by neybis** [comment]
Hahaha no worries :P I've been told I am a little verbose at times but I've also been told I can explain things so anyone could understand it. So hopefully that was helpful!

**Comment by carrigmore** [comment]
This is very helpful. How to close this one?

**Comment by neybis** [comment]
You got it ;)

**Comment by carrigmore** [comment]
Yes, just one question if I start insert at the place of a tab, the behavior of the cursor is still same even I have past that tab, and same if I use backspace to remove the letters. Please see screenshot
![cursor](https://cloud.githubusercontent.com/assets/8460701/10641022/4b943838-780f-11e5-8d25-4508e72612d6.gif)

**Comment by carrigmore** [comment]
Yest that is also correct. As you said "if you ever try to shrink it more than that, it jumps back to a "normal" tab size and shifts over a tab "column". This is why [self removeObjectFor... shifts when you type the 4th character; because your tab settings set a tab width of 4."

**Comment by neybis** [comment]
Yup, all of that functionality is correct.

It's important to remember that the tab character never goes away unless you press "delete" when your cursor is **before** the tab or you press "backspace" when your cursor is **after** the tab.

When you are inserting characters before the tab, the tab may appear to "shrink" and when enough characters are typed it will shift the tab to the right.

When you are deleting characters before the tab, the opposite will occur. The tab may appear to "grow" and when enough characters are deleted the tab will shift to the left.

So because you never deleted the tab, you will see the latter functionality (tab appears to "grow" and shifts left).

**Comment by carrigmore** [comment]
@neybis , thanks again. Now clear enough. Thanks you!
